### ISSUE TITLE
Refactoring view methods with blueprints

### ISSUE THREAD

**Issue by josh-thurston** [talkpython/data-driven-web-apps-with-flask#12]
Cannot figure out why everything stops working at the moment when I switch app.py over to use blueprints.  I am copying what you do in the video, but when i run app.py, I get a 404 return.

As soon as i switch back to original app.py setup, this work again.

**Comment by josh-thurston** [comment]
Ignore comment.  I looked at the code here in the repo.  I noticed that you added more to app.py that was not covered in the video.  I added the new lines of code and everything started working.

**Comment by mikeckennedy** [comment]
Hi @josh-thurston Glad you found the fix. Here is what's happening.

If you just run the app.py file, everything works as expected. If PyCharm somehow detects this as a flask project, it uses `$ flask run` which does NOT run the `main()` method. That's why you see the minor tweak in the code to still configure the system.
